### ISSUE TITLE
Handle `text/markdown` documents (on any URL)

### ISSUE THREAD

**Issue by broofa** [simov/markdown-viewer#10]
The current method of enabling this viewer on non-localhost URLs (via the options pane) is cumbersome and doesn't scale well.  For example, I'd like to publish a markdown page for project documentation.  While I'm okay saying, "This page requires the Markdown Viewer", I'm not okay saying "... and then go to options, the url for this site, then change the regex to `...(obscure regex here)...`".  That's just... gnarly.

I'd like to see an option (or default) for this viewer to handle any page served with `Content-Type: text/markdown`.  This is a de-factor standard, and the IETF has published an [informational spec](https://www.rfc-editor.org/rfc/rfc7763.txt), which I assume lends some degree of legitimacy to this.

Thoughts?

**Comment by simov** [comment]
There is a Chrome API called [webRequest](https://developer.chrome.com/extensions/webRequest) that doesn't yield permission warnings during install, and that most probably have access to the request headers, BUT it doesn't work with _event pages_.

_Event page_ is extension that auto unload itself from memory after short period of inactivity. You can see it in the Chrome's task manager.

The current method of detecting markdown pages is not optimal either because it awakes the extension on every tab change event.

I'll have to think about it and make some more research/testing.

**Comment by simov** [comment]
Oh that was only about the detecting of the `content-type` header. The origins should be added manually, otherwise Chrome yields the following warning: `Read and modify all your data on all websites you visit`. The regex is there for flexibility, you may want to limit the extension only to certain paths.

**Comment by broofa** [comment]
> Chrome yields the following warning: Read and modify all your data on all websites you visit

I'd be okay with that.

> The regex is used to detect the markdown files, because I don't have access to the actual request with the APIs that I'm currently using.

I understand.  Unfortunately it's just not very practical for making the plugin useful across a team or organization.

**Comment by simov** [comment]
I'll think about easier ways of adding new origins, like a button to allow them all.

Next I should probably switch to the webRequest API and ditch the whole _event page_ idea for now. With that API I should probably be able to implement two ways for detecting markdown files, the first one will use the headers and the second will use the url, if a regex was specified.

I'll let you know once I have something ready.

**Comment by simov** [comment]
I just published version 2.6 with small improvement about the way you add origins. Now you can enable the extension for [all origins](https://github.com/simov/markdown-viewer#add-all-origins). I also cleaned up the regular expression [a little bit](https://github.com/simov/markdown-viewer#specify-path-regexp). Still not *that* user friendly, I know, but it's very flexible.

And I'm yet to decide on the *event page vs header detection* case.

**Comment by simov** [comment]
wow this took me awhile ..

Actually I was browsing through some extensions and I found out about the [document.contentType](https://developer.mozilla.org/en-US/docs/Web/API/Document/contentType) property. And since I was already checking for `window.location` this was an easy fix.

So in version 3.1 the extension checks for the content-type header and only then it checks for the path. The header detection option is enabled by default and it can be found in the options page. You should receive the update automatically.

So @broofa to answer your initial question, here is what your users should do:

![allow-all](https://cloud.githubusercontent.com/assets/1694112/25531899/f0acaa10-2c33-11e7-9176-d2243ff5b541.png)

As long as the header detection option stays enabled and your server returns either `text/markdown` or `text/x-markdown` content-type header, the documents will be detected and rendered correctly even if the path matching regexp isn't correct.

I'm closing this issue now. Let me know if you have any other issues!
