### ISSUE TITLE
chromium settings for extension to launch only on click is not working.

### ISSUE THREAD

**Issue by py563** [simov/markdown-viewer#111]
I am using MS Edge (Chromium-Canary) and in egde(chrome)://extensions under details for each extension there is option to enable on all sites or some sites or on click. I don't know if it is browser issue as all other extensions do behave correct when onclick setting saying please refresh the page to use this extension. Whereas this shows the screen to select GFM and the themes or to go to advanced 
 rather then the general message.

I put request on Microsoft Insider Feedback hub to know more please follow [here](https://aka.ms/AA7g6y3)

**Comment by simov** [comment]
The OnClick option is intended for other types of Browser Extensions that are being activated on click. Markdown Viewer is not such extension and that's why when you click on the extension's button you see the popup with the options instead.

Markdown Viewer is unique in its own built-in way of handling permissions, so even if you enable it on All Sites, it really is going to be active only on the origins you explicitly allow in the Advanced Options page.
