### ISSUE TITLE
file:// URLs in Firefox 74 not rendered anymore

### ISSUE THREAD

**Issue by bidspells** [simov/markdown-viewer#116]
Dear all, 

I observed that a markdown file provided by a file:// URL is not rendered anymore in Firefox 74 (macOS). Instead a dialog appears to either save the file or open it with an external program. 

As I'm using this extension to view only local markdown files this new behavior is a kind of show stopper. 

Best regards,
Erik

**Comment by simov** [comment]
That's interesting because `file://` URLs aren't even supported on Firefox. No idea what changed on FF 74, but you can check out this https://github.com/simov/markdown-viewer/issues/90#issuecomment-592962363 on how accessing `file://` URLs behaves on other operating systems. 

We have no information as of now about whether Markdown Viewer works for `file://` URLs on FF and MacOS, so in case you can debug and figure this out, that would be really helpful.

**Comment by ywaby** [comment]
set markdown mime type as text/plain,firefox will open it.
linux add it to ~/.mime.types 
```
text/plain                                   md markdown
```

**Comment by aemonge** [comment]
It would be AWESOME to document this line xD

**Comment by callegar** [comment]
Despite that, my system recognizes those files as `text/markdown` and firefox does not open them via the extension.
I think that is because I have `retext` a markdown editor installed, that also installs its mime entry.
Is there a way to make firefox handle the `text/markdown` type via the extension or should it be considered a firefox bug being unable to do so?

**Comment by aemonge** [comment]
Also if we are in linux we should

**~/.local/share/mime/packages/text-markdown.xml**
```
<?xml version="1.0"?>
<mime-info xmlns='http://www.freedesktop.org/standards/shared-mime-info'>
  <mime-type type="text/plain">
    <glob pattern="*.md"/>
    <glob pattern="*.mkd"/>
    <glob pattern="*.mkdn"/>
    <glob pattern="*.mdwn"/>
    <glob pattern="*.mdown"/>
    <glob pattern="*.markdown"/>
  </mime-type>
</mime-info>
```

Then run `update-mime-database ~/.local/share/mime`

**Comment by simov** [comment]
All of that was tested and validated by my in Markdown Viewer v5.1, make sure you have a look at the new screencast too. There is a new document dedicated to firefox related issues and their workarounds [here](https://github.com/simov/markdown-viewer/blob/main/firefox.md). Let me know if you find any other issues.
