### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by Keith94** [simov/markdown-viewer#12]
Are there any plans to port the extension to Firefox using the WebExtensions API?

**Comment by simov** [comment]
That's a good idea actually, I've never thought about it. I'll do my own research and I'll let you know once I have something ready.

**Comment by Keith94** [comment]
Good to hear that. 👍

**Comment by huangjj27** [comment]
Is there a plan?

**Comment by huangjj27** [comment]
hi! I try to load the chrome extension into firefox, and it give some warnnings: 

```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
```

and because of this, options was not loaded:
![image](https://user-images.githubusercontent.com/8068443/31806536-453aef2e-b59b-11e7-8ec0-8949e067bf17.png)


It's seem to be the different structure that causes the problem. Maybe a few refactor works would solve it.

**Comment by huangjj27** [comment]
Hi! I'm now trying to port the extension to firefox, and I found some error from the `popup.js`:
![image](https://user-images.githubusercontent.com/8068443/31847958-424ee1bc-b659-11e7-909a-13117e9cc4f4.png)

it seems that in firefox extension, we can't simply define a global variable`res` and `state`.

**Comment by huangjj27** [comment]
ok, I mistake the point of `runtime` and `storage` entry. I found I could easily get the popup work by adding the [applications](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications) key to `manifest.json`. However, I can't get it render my chinese document and it seems that the unspecific encode of file causes the problem. I will get futhur when I'm spare

**Comment by simov** [comment]
Hi @huangjj27,

I've published the Firefox port of the extension here: https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-chrome/

The `applications` key is required because of the use of the `chrome.storage` API.

Currently the port works only if the `content-type` header of the resource is set to `text/plain`. If the resource is served with the correct `content-type`, either `text/markdown` or `text/x-markdown`, Firefox will try to download the file.

Another difference is that the Advanced Options page is disabled altogether and the extension have access to all origins by default.

Let me know if you have any questions.

**Comment by SuperHarmony910** [comment]
Thanks so much!
