### ISSUE TITLE
Why is there a min-width for the markdown-body?

### ISSUE THREAD

**Issue by afknapping** [simov/markdown-viewer#130]
Awesome plugin, thanks a lot 🎯 

I'm wondering about

https://github.com/simov/markdown-viewer/blob/d8d6507719cce3f34661ebd22a0bb2488def1281/content/index.css#L18

While I understand a max-width to keep things readable – why is there a min-width at all?

My usecase is zooming in to get larger type. Without the min-width, everything floats nicely. The min-width though forces a container that is larger than the viewport, resulting in overflow.

**Comment by simov** [comment]
This is only for the GitHub theme as stated above that line. That being said the GitHub theme have changed since then. The main goal of the GitHub theme is to give you as close as possible rendering output to the actual rendering for your readme on GitHub. The old content size was fixed to 882px up until the last design update. The other themes that come with this extension have dynamic width.

**Comment by afknapping** [comment]
i see, thank you for explaining.

i might be able to do a PR for an updated github theme – is this the source you would use? https://github.com/sindresorhus/github-markdown-css

**Comment by simov** [comment]
Yes, in fact I have it generated locally, it's just that I won't be able to publish it right now. Also note that the themes are located in https://github.com/simov/markdown-themes and then minified here with a script. In the meantime you can pull this repository and use the extension locally with the updated theme.

**Comment by afknapping** [comment]
awesome, thank you 👍
