### ISSUE TITLE
Possible to add Privacy Policy statement to readme?

### ISSUE THREAD

**Issue by RagingRoosevelt** [simov/markdown-viewer#134]
Would it be possible for a section to be added to the readme that addresses the extension's privacy policy?  I would think it could be something simple like:

"This most browser extensions, this extensions has access to the pages you have open.  All actions performed by this extension are local to your machine and nothing is sent to other computers.  This extension uses several common open source frameworks but those are contained within the extension and doesn't require external requests."

**Comment by simov** [comment]
All of these statements are part of my submission to the Chrome Store. Google added a new approval process for all extensions this year. Plus you can always install the extension manually [from here](https://github.com/simov/markdown-viewer#manual-install) meaning you can inspect the source code yourself.

**Comment by RagingRoosevelt** [comment]
I'm not seeing the privacy topic addressed on the chrome web store, am I looking in the wrong spot?

My motivation for asking is that my work has locked down chrome installs so that extensions have to be whitelisted.  Part of the process to get extensions approved is providing a link to the privacy policy.  I tried to get approval by mentioning that I'd looked through the source code and there's nothing concerning but that didn't fly, unfortunately.

Would it be OK for the readme to have a section outlining this topic?

**Comment by simov** [comment]
I understand. I just looked at the developer dashboard in Chrome Store and there is an additional 'Data Usage' section on the Privacy tab that is going to be available on my listing in the Chrome Store. Unfortunately I haven't published a new version in months.

These are the things that I have to comply with (that I do not):

- Sell user data to third parties
- Use or transfer user data for purposes that are unrelated to my item's single purpose
- Use or transfer user data to determine creditworthiness or for lending purposes

I can try packing up a few minor issues in the upcoming days and publish a new release with the Privacy policy options updated. Another option as you suggested is to add that to the readme as well although probably it's best to have it in Chrome store because that's tied to my actual submission there.

**Comment by simov** [comment]
I just released v4.0 where among other things I had to comply with the new policy:

![chrome-policy](https://user-images.githubusercontent.com/1694112/103092634-8ded1000-4600-11eb-8d23-e21a19efe77f.png)

Now this is a requirement in Chrome Store. Without it you can't even submit your extension anymore.

Here is the full text of the policy linked in the above screenshot: https://developer.chrome.com/docs/webstore/program_policies/

There is nothing else regarding policy in the new Developer UI, or in the extension listing. So I guess that's the only policy that you can have now.

Let me know if that works for you.

**Comment by RagingRoosevelt** [comment]
Yeah, that works!  If the approval folks at work won't accept the developer program policies, then at least I can point them to this issue and they can see it here =D

Thanks!

**Comment by simov** [comment]
Turns out there is a Privacy Policy URL in the new Developer dashboard, but it's for the entire account, meaning applies to all extensions in it.

However since I don't collect any user data:
![privacy-policy](https://user-images.githubusercontent.com/1694112/103353826-86bb7b80-4ab2-11eb-8829-ab9e188a59b9.png)

it's not required for me because there is nothing to comply with. 

I heard from other developers that once you start collecting data the Privacy Policy URL for your account becomes mandatory. Again this is controlled by the new reviewing process every time you submit a new version of your extension.
