### ISSUE TITLE
Suspected compatibility issue with Chrome 100.0.4896.127

### ISSUE THREAD

**Issue by shiliang26** [simov/markdown-viewer#176]
I haven't been able to render Markdown since updating my Chrome to Version 100.0.4896.127.
Could you confirm this? Are there any workaround?

**Comment by simov** [comment]
Just updated my Chrome version and everything seems to be working on my end. You can verify if your access to local file URLs is enabled for the extensions, in case you use that. Otherwise go to the advanced options for the extension and take a look at your origins, in case they have a a little `refresh` label on them then you have to click on the Refresh button for all of them. If that's not the case then I would suggest you to remove and re-install the extension, nothing have changed here since long time ago so it should work.

**Comment by shiliang26** [comment]
Thanks, that was helpful.
Apparently the local file access was disabled somehow.
