### ISSUE TITLE
Firefox extension listing outdated

### ISSUE THREAD

**Issue by keunes** [simov/markdown-viewer#188]
Hello,

Just discovered this - nice work! :-)

The [Firefox extension listing page](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-chrome/) still has the warning
> Currently file:// URLs are not supported!

But that doesn't seem to be the case: it works in practice and local URLs are listed also in the feature list here on GH.

Would probably be good to update the description :-)

**Comment by simov** [comment]
Thanks for reporting this, however, on my end on Linux local file URLs are still not being loaded in Firefox, so maybe it is some sort of a settings on your end.

**Comment by codysims** [comment]
Great extension, thanks! Any plan to update Firefox to 5.0?

**Comment by simov** [comment]
Yes, and I hope that will be possible soon. Unfortunately Firefox lags behind in terms of manifest v3 support, which I had to migrate to on Chrome, before its sunset got postponed again back in December 2022. I will be checking Firefox again in March and depending on the outcome of that we will have to wait a bit longer or have the v5 released sooner. Generally speaking if all manifest v3 features are working on that said stable release of Firefox I will be waiting for at least the next stable release before publishing so that people can have the chance to update their browsers.

**Comment by simov** [comment]
Markdown Viewer v5.1 was released on Firefox with all of that and more, check it out. Also there is a new file designated specifically to [firefox](https://github.com/simov/markdown-viewer/blob/main/firefox.md) related issues and workarounds.
