### ISSUE TITLE
if ALLOW ALL in ADVANCED OPTIONS will change page that end with ".md"

### ISSUE THREAD

**Issue by DIYer22** [simov/markdown-viewer#194]

**Comment by DIYer22** [comment]
ALLOW ALL in ADVANCED OPTIONS 

![image](https://user-images.githubusercontent.com/10448025/208240280-53e42c85-84c8-47df-b943-beaa263dcbfd.png)

Then, I it will change any page that end with `.md`, for example: https://github.com/simov/markdown-viewer/blob/main/README.md

![image](https://user-images.githubusercontent.com/10448025/208240342-c3bdbd4a-4dc7-41ef-95e6-ee946e1ec20d.png)

Which the page should be :
![image](https://user-images.githubusercontent.com/10448025/208240376-14f69380-8fc1-4dce-bdeb-3549ec36a9fe.png)

**Comment by simov** [comment]
Yes, have a look at the documentation https://github.com/simov/markdown-viewer#path-matching-priority

Also, do note that:

> It is recommended to explicitly allow only the origins that you want the extension to have access to.

**Comment by DIYer22** [comment]
Thank you for the amaze works and reply.
I have been using this extension for several years, and it has been working fine before, this problem happend  a few days ago, so I openned the issue.

**Comment by DIYer22** [comment]
By the way, I fix my problem by write a regular expression for `ADVANCED OPTIONS` that matches all URLs with a domain name is an IP address and ".md" at the end.

```
https?://\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:?[\w\./-]*\.(?:markdown|mdown|mkdn|md|mkd|mdwn|mdtxt|mdtext|text)(?:#.*|\?.*)?$
```

**Comment by simov** [comment]
Interesting, not sure why it could fail because of the latest update, though note that this was a significant update too, among other things it was a migration from manifest v2 to manifest v3 for chrome extensions. I'm glad that it worked out in the end for you. Though again, you really don't need to enable the extension for all origins, it's always better to enable it only for the origins and paths that you expect to read markdown files on.
