### ISSUE TITLE
No Effect

### ISSUE THREAD

**Issue by PaltryProgrammer** [simov/markdown-viewer#198]
Upon install and viewing of sample **md** page link below I see no mark down formatting as demonstrated in attached PNG Also please see Markdown-Viewer options in Edge as shown in attached PNG Kindly Advise Thank You
https://gist.githubusercontent.com/rt2zz/e0a1d6ab2682d2c47746950b84c0b6ee/raw/83b8b4814c3417111b9b9bef86a552608506603e/markdown-sample.md
![Sample MD Page](https://user-images.githubusercontent.com/48535920/211182708-e07b6654-4aaf-4117-93c6-30f296e5ca95.png)
![Options](https://user-images.githubusercontent.com/48535920/211182711-828edd2a-c314-4ca2-a821-fe8a2b02d7e4.png)

**Comment by simov** [comment]
Hi, for remote origins you need to enable them explicitly, I know it currently says 'Site access - On all sites', but it's not really like that. So all you need to do is:

- click on the extension button (the little 'm')
- inside the popup click 'Advanced Options'
- on the newly opened page paste the above URL into the text box next to 'Allowed Origins' and click 'Add'

This will extract the domain name out of the URL and ask for permissions to access that origin. Click 'Allow'.

This is how you enable the extension for a specific remote origins, it have to be done explicitly, and it is recommended to do it only for the origins that you want, instead of using the 'Allow All' button which has some other implications to keep in mind.

The 'Allow access to file URLs' that you see enabled in your options is for markdown content served on the file:// origin, meaning through the built-in file manager for content on your local file system.
