### ISSUE TITLE
Unsuccessful Mermaid

### ISSUE THREAD

**Issue by PaltryProgrammer** [simov/markdown-viewer#199]
Greetings i visited mermaid example page link below provided at github site link below , pasted mermaid address into "Allowed Origins" clicked "ADD" . Result is shown in GIF . Kindly Advise . Thank You

https://github.com/simov/markdown-syntax
https://github.com/simov/markdown-syntax/blob/main/mermaid.md
![Mermaid](https://user-images.githubusercontent.com/48535920/211228168-dabb18f4-ed53-4a62-926a-042aebf509b7.gif)

**Comment by simov** [comment]
This is an HTML page served on an URL that ends with `.md` as if it was a markdown document, but it is not. github.com does not serve markdown files, it serves HTML files instead. You have to click on the `raw` button for that file which will take you to https://raw.githubusercontent.com/simov/markdown-syntax/main/mermaid.md instead. This is the origin that you have to enable, and the one that Markdown Viewer can operate on, because it serves the markdown document. You can read more about it in the [examples section](https://github.com/simov/markdown-viewer#syntax-examples).
