### ISSUE TITLE
Tables' indentation doesn't work

### ISSUE THREAD

**Issue by aercolino** [simov/markdown-viewer#20]
case 0: a table at indentation level 0, after a paragraph (at level 0) -- this should render the table not-indented

|A|B|
|---|---|
|1|2|

* case 1: a table at indentation level 1, after a list item at level 1 -- this should render the table indented once

    |A|B|
    |---|---|
    |1|2|
    
    * case 2: a table at indentation level 2, after a list item at level 2 -- this should render the table indented twice
    
        |A|B|
        |---|---|
        |1|2|    

case 3: a table at indentation level 1, after a a paragraph (at level 0) -- this should render the raw text into a code block

    |A|B|
    |---|---|
    |1|2|

**Comment by aercolino** [comment]
The indentation _per se_ works fine, but instead of rendering them, the tables are shown raw.

**Comment by simov** [comment]
Yep, this seems to be broken in the underlying parsers that the extension uses. Note that the extension supports [even more compilers](https://github.com/simov/markdown-viewer#more-compilers) and it seems that `markdown-it` covers the above cases, I just checked.

The reason why there are only 2 compilers currently in the published version is because I try to strike a fine balance between features and too much cognitive load. Also it's hard for me to pick and choose a single (the best) compiler because each have it's own shortcomings.

Lastly all of these markdown compiler/parser projects are open source, so we should notify their maintainers about these issues and most probably they will be happy to fix them. _Marked_ isn't actively maintained, but maybe the _Remark_ maintainers would be happy to fix it.

**Comment by aercolino** [comment]
https://github.com/wooorm/remark/issues/256

**Comment by simov** [comment]
@aercolino I've updated to the latest version of Remark and I can confirm that this bug was fixed. I'm going to publish the next release in the upcoming days :+1:
