### ISSUE TITLE
mathjax render "\boldsymbol" will crash

### ISSUE THREAD

**Issue by DIYer22** [simov/markdown-viewer#204]
![image](https://user-images.githubusercontent.com/10448025/215316691-2aed4eaa-51da-4653-abc3-7eb5a307ea65.png)

- My temporary solution is replacing "\boldsymbol" to "\textbf"
- There is no problem with the previous version markdown-viewer

Here is the test markdown string
```md
$$
\textbf{A}
\boldsymbol{A}
$$
```

**Comment by simov** [comment]
Interesting, maybe a trimmed the MathJax library too much. It seems like this is an extension that is not part of the Markdown Viewer v5 bundle. The reason why this works on Markdown Viewer v4 is because I was loading the library directly from cdnjs and therefore the entire build was available there. But with Markdown Viewer v5 I had to migrate to manifest v3 and therefore bundle all libraries with the extension, which is fine, but MathJax is a really large library so I tried to trim it down without knowing all of the specifics on how it works.

**Comment by DIYer22** [comment]
At least the crash can be fixed first. 
If I turn on `autoreload` and change the md file, than markdown-viewer will not crash. But it still can't  recognize "\boldsymbol", like  this:
![image](https://user-images.githubusercontent.com/10448025/215320779-f1ef9d97-f2e0-42ca-b6af-bcc5e72cd0a8.png)

**Comment by simov** [comment]
This was fixed in v5.1, now all tex/latex extensions for mathjax are bundled with the extension. You can take a look at the updated mathjax section of the mathjax [examples](https://github.com/simov/markdown-viewer#syntax-examples) that I used for testing this.
