### ISSUE TITLE
Markdown Viewer not responding?

### ISSUE THREAD

**Issue by xjtumedicine** [simov/markdown-viewer#210]
The p
![Snipaste_2023-04-06_13-49-27](https://user-images.githubusercontent.com/51862156/230491155-495bfc29-5730-4e30-9323-95fd4d774aa1.png)
revious commands used to work effectively and were great, but in the past two days, despite changing the settings and themes, there has been no response. Has anyone experienced a similar problem?

**Comment by simov** [comment]
This may be caused by the underlying service worker crashing. It is a known issue in Manifest v3 that the Chromium team is working on. One thing you can try is to restart your browser. If that didn't work then maybe you can go to chrome://extensions, enable the developer switch and try to restart the extension. As a last resort you may have to re-install it. Hopefully this will get fixed soon in Chromium.

**Comment by xjtumedicine** [comment]
I just find It works fine now. Thank you.
