### ISSUE TITLE
How can I change the syntax highlighting for code blocks

### ISSUE THREAD

**Issue by Thweki** [simov/markdown-viewer#218]
>Thank you very much for the plugin you've developed. It has been incredibly helpful to me.

I want the rendered Markdown file to be consistent with my system and Vim theme. To achieve this, I have written a CSS file.

At first, everything went smoothly, but when it came to code blocks, I became unsure of how to make the syntax highlighting consistent with the overall theme.
<img width="1112" alt="image" src="https://github.com/simov/markdown-viewer/assets/42636863/a2db2f4c-6d4f-4664-9fb6-24aa56ee6490">
Do you have a way to modify the syntax highlighting for code blocks? 
Thank you very much.

**Comment by Thweki** [comment]
I'm using the Everforest theme.

**Comment by simov** [comment]
The syntax highlighting for code blocks is being done using [prismjs](https://prismjs.com/), you can find their stylesheets in their repo. 



I think you will have to inspect the code blocks in your browser and see which styles are being applied, then maybe add a `style` tag at the bottom of your markdown file (you should be allowing HTML tags in your parser settings) and add your style overrides there with bigger weight than the ones used by the viewer so that they can take effect.

I haven't tried this so it may not work, also having styles in your document is not ideal, but it's worth a try at least.

**Comment by Thweki** [comment]
Thank you for your reply. I changed the style of prism. 
Now it looks good. You`re my hero!

**Comment by Thweki** [comment]
Thank you for your reply. I changed the style of prism.
Now it looks good. You`re my hero!

**Comment by simov** [comment]
Custom theme support landed in v5.3, have a look at the [documentation](https://github.com/simov/markdown-viewer?tab=readme-ov-file#custom-theme)

When you select the CUSTOM theme at the bottom of the themes dropdown you get a blank theme. Then you can add a style tag in your markdown and create your own theme, here is an [example](https://gist.github.com/simov/2a074a1c0123e6ba4bc2bfa6a67d3203). Once you are ready go to the Advanced Options page and click on Settings in the header, if the CUSTOM theme is selected there will be a button below to select your .css file and make it permanent. Don't forget to remove the inline tag from your document. You can also update or remove the uploaded custom theme.
