### ISSUE TITLE
Custom Stylesheets

### ISSUE THREAD

**Issue by DavidTimms** [simov/markdown-viewer#5]
First of all, I'd like to thank you for developing this extension. It seems to be the best of the Markdown Viewers available on the Chrome Web Store.

One feature which I wish was supported is custom stylesheets. The provided themes are great, but I wish I could tweak the CSS on a couple of them to suit my preferences. I think there would be demand for this from other users too, given Markdown's popularity among developers.

Are you open to contributions on this? If so, I could try to implement something over the next couple of weeks and submit a pull request.

Thanks,
David

**Comment by simov** [comment]
Hi, @DavidTimms, thank you for your interest in this extension!

My approach to Chrome Extension is exactly the same as with NodeJS modules for example. Each module/extension should do only one thing. Easier to maintain, easier to reason about.

So what you want is actually a *styling* extension like [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe) which have built-in UI for updating user styles.

Generally the problem with such Chrome extension that needs to store potentially very large strings (your styles) needs some sort of storage. The usual Chrome Sync API is not designed for such strings and because of that have very strict limitations. The other most obvious place to store the styles is on a third party server, that's important if you want your styles to be synced across multiple devices.

So instead of using Stylish I'm using my own extensions for that called [Styler](https://github.com/simov/styler). The difference is that your styles are stored in files locally where the extension can reach them. The downside of this approach though is that I can't publish this extension on the App Store, because once it's bundled the extension's files cannot be changed.

Now what I would do is just use Styler to inject additional css file with my custom styles, when I'm looking at markdown files. Currently Styler expects only [URLs with a host](https://github.com/simov/styler/blob/master/background/utils.js#L7) but that can be changed easily. BTW the `url.host` that you see there is passed from the content script and it's the `window.location.host` so you have everything that you can usually find in `window.location`.

**Comment by DavidTimms** [comment]
Thanks for the reply @simov.

I can see how syncing the custom styles would be difficult with Chrome Sync, and you're quote right about doing one thing well. I hadn't considered using another styling plugin, but that actually solves my problem completely!

Thanks again
