### ISSUE TITLE
incompatiblity with other extensions: blank page instead of (rendered) Markdown

### ISSUE THREAD

**Issue by salim-b** [simov/markdown-viewer#72]
As soon as I allow a domain in the advanced options, only a blank page is displayed instead of the actual (rendered) Markdown content.

E.g. this Markdown file I can't see: https://gist.githubusercontent.com/salim-b/b4442f4464976d5fd31babeb0b709c1a/raw/4748002bf3f353a96d78bf0e967a906d10f6b880/footnote_example.md

When I disable certain other Chrome extensions, markdown-viewer renders the file properly. I had to disable _all_ of the extensions below:

- [Hugo - the extension you really want!](https://chrome.google.com/webstore/detail/hugo-the-extension-you-re/hbaembbfbmpbjgkgcjcfonnimlekbfea)
- [Markdown Here](https://chrome.google.com/webstore/detail/markdown-here/elifhakcjgalahccnjkneoccemfahfoa)
- [MyJDownloader Browser Extension](https://chrome.google.com/webstore/detail/myjdownloader-browser-ext/fbcohnmimjicjdomonkcbcpbpnhggkip)
- [Translator](https://chrome.google.com/webstore/detail/translator/blndkmebkmenignoajhoemebccmmfjib)

These extensions all have the permission granted to read and modify all the data of the sites I visit. I guess the incompatibily could be due to some kind of race condition about modifying the website data?

I'm using Chromium 70.0.3538.110 on Ubuntu 16.04.

**Comment by simov** [comment]
Thanks for the detailed bug report! Other users have reported similar issue. It is related to modifying the content of the page indeed, I'll definitely look at it.

**Comment by fish-face** [comment]
I also get a blank page instead of the rendered markdown - but only *sometimes*. If I refresh enough times, eventually the correctly rendered markdown will be displayed! So it definitely sounds like a race condition.

I disabled all the extensions which had scripts loaded on the markdown document page (which is a local file) and got it to render most of the time, whereas with these extensions loaded, it would be blank most of the time. They were:

* LastPass
* uBlock Origin
* find+ | Regex Find-in-page tool

**Comment by jsejcksn** [comment]
Visual example of this bug:

![markdown-viewer-bug](https://user-images.githubusercontent.com/868251/54080411-6e161c00-42b4-11e9-9e02-880379534c63.gif)

**Comment by simov** [comment]
Just published a fix in v3.7, you should receive the update shortly. Let me know if you still have issues.
