### ISSUE TITLE
Browser action popup width

### ISSUE THREAD

**Issue by ValentinG0** [simov/markdown-viewer#78]
The content of the popup is too wide. (See the screenshot)
No problem with the height, the popup fits correctly.

![image](https://user-images.githubusercontent.com/6833309/50593273-f8e33080-0e97-11e9-85e4-9e04345429fd.png)

**Comment by simov** [comment]
Thanks for the info, @ValentinG0. I just tried it on Nightly 66 and it seems to be working well:
![firefox-66](https://user-images.githubusercontent.com/1694112/50611677-e987d580-0edf-11e9-85a7-203c77567ad3.png)

So it's either fixed in 66 or it's something related to the underlying OS used? I'm on Linux.

**Comment by ValentinG0** [comment]
Yes, it seems to be related to the underlying operating system used. I tried on Debian 9.6 and Firefox ESR 60.4.0, it works fine. But with Windows 10 and Firefox ESR 60.4.0, it does not work.

I do not know if the problem comes from the extension or Firefox.

**Comment by simov** [comment]
The width of the popup is fixed, that's for sure. No idea if there are any recommendations about the CSS used in the overflow menu. But being broken only on Windows is strange.

I'll research more once I get to it. Let me know if you find anything else.

**Comment by simov** [comment]
All of that correctly working in latest Markdown Viewer v5.1
