### ISSUE TITLE
Feature: Support the "on click" permission option

### ISSUE THREAD

**Issue by jsejcksn** [simov/markdown-viewer#89]
and include the option just for file-property matching in the options view. This will add an option for users who have need for increased security to be able to use the extension.

<img width="680" alt="on-click" src="https://user-images.githubusercontent.com/868251/54080464-dca7a980-42b5-11e9-82c8-e8c01a435fc1.png">

**Comment by jsejcksn** [comment]
See Install and manage extensions > Let extensions read and change site data

on https://support.google.com/chrome_webstore/answer/2664769

**Comment by simov** [comment]
TBH I'm not even sure how exactly these new options in Chrome works. They all seem a bit wonky to me. What this extension is doing, however, long before anyone though about this issue is actually allowing you to choose your origins.

The `On click` option was introduced by Google to allow the users to limit the extensions that require access to all origins during install time. Markdown Viewer is clearly not such extension, and allowing access to all origins was never encouraged, because it's simply not needed, but again - it's up to you.

**Comment by simov** [comment]
This isn't going to be implemented, but thanks for the feedback. Also, checkout Markdown Viewer v5 that just got released.

**Comment by jsejcksn** [comment]
> This isn't going to be implemented, but thanks for the feedback.

@simov Thanks for the message! You're the code owner, so this is of course your decision. Would you like to offer any insight into why you don't want to empower users with this security/privacy choice?

**Comment by simov** [comment]
Honestly, I have no idea how this could be implemented on top of my head .. Generally speaking Markdown Viewer was never designed to work that way, which isn't to say that it won't be possible.

**Comment by simov** [comment]
But note that Markdown Viewer v3 is also using the latest manifest v3 which is supposed to be much more secure, at least that's how they are promoting it.
